# Project information
site_name: Niflheim Quickstart
site_url: https://asm-dtu.gitlab.io/niflheim-quickstart
docs_dir: docs

# Theme settings
theme:
  name: material

# Navigation menu
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Submit jobs: slurm.md
  - Software Modules: modules.md
  - File editing: editing-files.md
  - Useful Linux Commands: linux.md
  # - More Resources: resources.md

# Plugins
plugins:
  - search
  
markdown_extensions:
  - toc:
      permalink: "#"
